builds:
- env:
    - CGO_ENABLED=0
  main: ./cmd/tagger/
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
  ldflags:
    - -s -w -X main.ldVersion={{.Version}} -X main.ldTimestamp={{.Timestamp}}
archive:
  replacements:
    386: i386
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
sign:
  artifacts: checksum
